### ISSUE TITLE
Refactoring code

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#10]

**Comment by fedorov** [comment]
Need to discuss with @PeterBehringer:

Looking at https://github.com/SlicerProstate/SliceTracker/blob/reg_update/SliceTracker.py#L2128

Does it make sense to change the name of that function to be consistent with applyReRegistration()? Also, need to consider if common items should be factored out. The only difference is whether initial transform is supplied or not. There is a lot of redundancy between these two functions, and they are way too long - probably should be broken down into sub-functions (e.g., transform targets can be a separate function).

**Comment by che85** [comment]
Reopening since refactoring is one of the last issues that might be closed

**Comment by che85** [comment]
@fedorov I would like to invest some time into this issue because we added so much code in the last weeks caused by new use cases/issues/features and I just want to make sure, that it is clean. Maybe I can do that besides a new project?

**Comment by fedorov** [comment]
yes, definitely - these two will need to be balanced
