### ISSUE TITLE
Manual adjustment of the targets

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#106]
If registration fails, it should be possible and easy to adjust the locations of the targets in 3d. For this, need to:
 - switch to either 3-over-3 layout (pre-procedural t2 in the top row, cover prostate in the bottom), or to 2-over-2 layout (axial, sag and cor for cover prostate and axial for planning t2)
 - when target is clicked in the target list, synchronize the cover prostate views to the positions of the target in cover prostate, and at the same time synchronize positions of the planning image(s) to the same target there
 - annotate slice viewers preop/intraop
 - when target is moved in intraop, synchronize all intraop views to the new location
 - "lock" preop target to prevent accidental modification

**Comment by che85** [comment]
@fedorov Would it make sense to lock needle image registration's targets as well? Since they don't have any impact on following needle image registrations, the user should only be able to move the Cover Prostate targets (which would have an impact on all following registrations)

**Comment by fedorov** [comment]
I think they should not be locked at the time registration is evaluated. Registration still can fail, and manual adjustments might be needed when the operator needs to select template hole based on needle registration. Outside registration evaluation step they can probably be locked.

**Comment by che85** [comment]
@fedorov How should images be placed in 2-over-2 layout? I would assume to place the images like in a Four-Up view and replacing the 3D view by planning t2...

**Comment by fedorov** [comment]
yes, that's what I thought too

**Comment by che85** [comment]
@fedorov how would you expect the user to get into the 2-over-2 layout? Any specific button like "manually adjust targets" or just another entry in the layouts dropdown (which would make it less visible to untrained users)?

**Comment by che85** [comment]
@fedorov Another question. Assuming that the registration fails (Cover Prostate) and the user changes the target positions manually, he/she would probably skip the registration result, because the registration failed? If the user skips the Cover Prostate registration result, SliceTracker would not allow to register needle images because the registration (as it currently is) uses the rigid transform of the previous registration as the input. Sometime in the past, we decided to disable the "track targets" button in such situations.

How should we handle this?

**Comment by fedorov** [comment]
>  how would you expect the user to get into the 2-over-2 layout? Any specific button like "manually adjust targets" or just another entry in the layouts dropdown (which would make it less visible to untrained users)?

I propose that the "registration failed" option should be enabled for the cover prostate registration. Then if it failed, there should be a choice to redo segmentation, repeat cover prostate or manually adjust the targets, and if it is the latter - go to the 2-over-2 layout. 

As I think about this now, it is also possible that registration fails "catastrophically" and targets are completely in the wrong place. In this situation it may be easier to place new targets instead of moving existing ones ... a lot of options, I need to think what is the best way to present to the user.

**Comment by fedorov** [comment]
>  If the user skips the Cover Prostate registration result, SliceTracker would not allow to register needle images because the registration (as it currently is) uses the rigid transform of the previous registration as the input.

I think if cover prostate fails, and there is no second cover prostate and user wants to "track targets", then prostate should be segmented the first time they try, and after that it can proceed as normal.

**Comment by che85** [comment]
>I propose that the "registration failed" option should be enabled for the cover prostate registration. Then if it failed, there should be a choice to redo segmentation, repeat cover prostate or manually adjust the targets, and if it is the latter - go to the 2-over-2 layout.

Ok sounds good to me. 

>As I think about this now, it is also possible that registration fails "catastrophically" and targets are completely in the wrong place. In this situation it may be easier to place new targets instead of moving existing ones ... a lot of options, I need to think what is the best way to present to the user.

**Comment by che85** [comment]
>As I think about this now, it is also possible that registration fails "catastrophically" and targets are completely in the wrong place. In this situation it may be easier to place new targets instead of moving existing ones ... a lot of options, I need to think what is the best way to present to the user.

Yeah, we really need to think about such a "mode" for replacing the existing targets (only in Cover Prostate registration step)

**Comment by che85** [comment]
>I think if cover prostate fails, and there is no second cover prostate and user wants to "track targets", then prostate should be segmented the first time they try, and after that it can proceed as normal.

Makes sense to me.

**Comment by che85** [comment]
>I propose that the "registration failed" option should be enabled for the cover prostate registration. Then if it failed, there should be a choice to redo segmentation, repeat cover prostate or manually adjust the targets, and if it is the latter - go to the 2-over-2 layout.

@fedorov should the user be prompted? Currently we have those buttons  in the evaluation interface available except of the "manually adjust" and "repeat - where I think u meant that another Cover Prostate image is taken?"

**Comment by che85** [comment]
>As I think about this now, it is also possible that registration fails "catastrophically" and targets are completely in the wrong place. In this situation it may be easier to place new targets instead of moving existing ones ... a lot of options, I need to think what is the best way to present to the user.

The mode should include something like selecting existing one which shall be replaced with a new one. That way we are able to make sure that the name is kept and that exactly the same number of targets can be replaced and nothing else.

**Comment by che85** [comment]
Steps for replacing targets:
1. select target which should be replaced
2. push button "replace" or with selection the replacement mode is already activated
3. user can set a new target
4. SliceTracker removes old target or just sets the position of the existing target to the new target's position
5. unnecessary target will be removed

@fedorov  What do you think?

**Comment by fedorov** [comment]
Great idea! But I think we can make it even simpler. How about "Move on click" button for each fiducial? So instead of replace and remove the old one, we explicitly say we move the selected target to the point where the user clicks?

**Comment by che85** [comment]
Yeah that makes sense. So would it be another column in the target table for each fiducial or would we have a button outside of the target table which is activated in that mode whenever a fiducial is selected from the target table?

**Comment by che85** [comment]
What would be the workflow after moving the targets? Pushing a accept button? What happens to the Cover Prostate result then? Would the segmentation mask be used for following registrations? If so, we would "approve" the Cover Prostate registration result with accepting the moved targets.

**Comment by fedorov** [comment]
Let's brainstorm those issues tomorrow over hangout?

**Comment by che85** [comment]
:+1:

**Comment by fedorov** [comment]
In preparation for this discussion, can you put together a diagram of the workflow steps and all decision branches? It would be very very helpful, both for the discussion and documentation.

**Comment by che85** [comment]
sure

**Comment by fedorov** [comment]
> So would it be another column in the target table for each fiducial or would we have a button outside of the target table which is activated in that mode whenever a fiducial is selected from the target table?

I like the idea to have a button in the table for each target. This way it is one click less. It is important that in the cases when the target was manually moved, we record this while saving the data.

> What would be the workflow after moving the targets? Pushing a accept button? What happens to the Cover Prostate result then? Would the segmentation mask be used for following registrations? If so, we would "approve" the Cover Prostate registration result with accepting the moved targets.

Yes, I think it should be accept, but we record which targets were moved, and their initial locations produced by registration. Yes, I think we should use the mask for the subsequent registrations. If subsequent registrations fail, the operator has the option to re-segment.

**Comment by che85** [comment]
> I like the idea to have a button in the table for each target. This way it is one click less. It is important that in the cases when the target was manually moved, we record this while saving the data.

An easier solution would probably be to listen to double click signals on the target table rows:

1. double click on target row enters mode for moving target
2. cancel movement mode with another dblclick or finish movement with setting point in viewers

Otherwise we would need to create and connect a button for each target in that target table which always would be recreated while changing current targetlist (bspline, affine, rigid) 

Another advantage would be, that we don't need to add another column. We can introduce the functionality to the user with a tooltip, info sign or something else.

**Comment by fedorov** [comment]
That's fine. I also just thought about this - would be great to change the mouse cursor when "move target" mode is enabled.

**Comment by che85** [comment]
![image](https://cloud.githubusercontent.com/assets/10195822/13232683/4128c42e-d97e-11e5-9b1e-e23d7bf46d9c.png)

@fedorov What do you think about adding a annotation while the target moving mode is active for a target. The user would immediately see, that something changed in the view.

**Comment by fedorov** [comment]
yes, I agree, but it is not typical to use that to communicate mouse mode to the user, so I would prefer to have the mouse mode icon. What you propose is ok for now though. At this point it is most important to test the whole workflow.

**Comment by che85** [comment]
@fedorov should all intraop target be eligible for moving? Otherwise I would to bSpline targets only.

**Comment by fedorov** [comment]
yes, I think it should be possible to adjust the targets independently of what is the step of registration selected. If rigid looks better than bspline, the user should be able to start from that one for adjusting the targets. Maybe it makes sense to avoid the notion of "bspline" etc in the code, but instead have something like "approvedTarget", and initialize it to the targets as they are at the time of approval?

**Comment by che85** [comment]
yes ok makes sense to me

**Comment by che85** [comment]
If during target movement mode another target is selected from the target table, what should happen?

a) target movement mode will be disabled
b) target movement mode changes to the newly selected target (slice annotation will be updated)

I tend to implement a) because the slice position can completely change and maybe the user didn't have any idea about the position of the newly selected target. Another argument for disabling is, that the user could accidentally click into the slice view and change the position (This would be fatal, since we don't have any history - undo or redo)

**Comment by fedorov** [comment]
I agree a) looks better

**Comment by fedorov** [comment]
One idea is to save the fcsv of all registration stages as soon as registration is completed. At the time registration result is approved (after manual adjustment, if needed) approved.fcsv list of targets is also saved, which may be the same or different from the individual registration stage result fcsv
