### ISSUE TITLE
If cover prostate registration completely fails, allow user to track targets in needle images

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#107]
If cover prostate fails, and there is no second cover prostate and user wants to "track targets", then prostate should be segmented the first time they try, and after that it can proceed as normal.

**Comment by che85** [comment]
@fedorov Is this issue still needed to get fixed? 

Current solution would be: user can modify target positions in Cover Prostate registration and those targets will be registration to subsequent needle images.

Even when there is no preop image, we are now able to proceed with intraop only so I think that this should not be separately implemented. 

What do you think?

**Comment by fedorov** [comment]
Yes, definitely - reposition ING of targets functionality takes care of this issue.
