### ISSUE TITLE
Document file names and conventions used for saving results

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#108]
Let's have a github project wiki page with this documentation.

**Comment by che85** [comment]
See https://github.com/SlicerProstate/SliceTracker/wiki/Document-file-names-and-conventions-used-for-saving-results

**Comment by fedorov** [comment]
Sorry I didn't respond. I wanted to think about it first, but didn't make the time yet.

**Comment by fedorov** [comment]
@che85 few suggestions
* I would not use series name in the file name - it has spaces and may complicate parsing of that data later. Series number is usually unique and should be sufficient.
* let's also save the fiducials for the segmentations created using VolumeClip
* Zframe transform should have the series number as prefix, since there may be multiple z-frames
* registration transforms have extension .fcsv in the documentation wiki - I hope this is just a typo in the wiki?

**Comment by che85** [comment]
@fedorov

> let's also save the fiducials for the segmentations created using VolumeClip

How should I name that file?

> registration transforms have extension .fcsv in the documentation wiki - I hope this is just a typo in the wiki?

You are right. It was only a typo

**Comment by fedorov** [comment]
> > let's also save the fiducials for the segmentations created using VolumeClip

> How should I name that file?

Any name is fine, as long it is used consistently and is documented. How about
```
<series_number>-VolumeClip_points.fcsv
```
?

**Comment by che85** [comment]
:+1:

**Comment by che85** [comment]
@fedorov What about saving the volumes of the results like bSpline volume ...? I implemented this feature, but we are currently not using it.

**Comment by fedorov** [comment]
yes, sure - let's save that too

**Comment by fedorov** [comment]
Christian, we also need to make sure we save the registration assessment score!

**Comment by che85** [comment]
@fedorov how would you do that? In a separate file or in the JSON file (where it is already saved)

**Comment by fedorov** [comment]
I didn't know it is saved in json, I missed it. 

Can you add an example json to the wiki, and then close this issue?

**Comment by che85** [comment]
See https://github.com/SlicerProstate/SliceTracker/wiki/Document-file-names-and-conventions-used-for-saving-results#json-results-file-continueload-case for JSON example

**Comment by fedorov** [comment]
👍
