### ISSUE TITLE
Error Checking

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#11]
- We cannot expect the user to always select everything correct
- The current state of that module is:
-- no checks if directories or files exist 
-- expectations of filenames which can vary, e.g. "t2-label.nrrd" and "t2ax-label.nrrd"
-- especially no checking for valid nodes that hinder the execution, e.g. if "t2-label.nrrd" could not be loaded...

**Comment by PeterBehringer** [comment]
@che85 this is already fixed, right?

**Comment by che85** [comment]
Let me see. I will go over it to ensure that we don't forget anything
