### ISSUE TITLE
SliceTracker should approve the selected registration type rather than only a result in general

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#113]
Currently SliceTracker only approves the registration result by itself instead of approving the currently selected registration type (rigid, affine, bSpline).

**Comment by che85** [comment]
Furthermore, with selection of the approved registration result afterwards in the targeting step, the approved registration type and the approved targets should be displayed

**Comment by fedorov** [comment]
> the approved registration type and the approved targets should be displayed

and saved!
