### ISSUE TITLE
Using newly created segmentation label when retrying needle image registration

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#114]
To clarify this:

If Cover Prostate registration result has been approved and during a Needle Image registration result is not satisfying, the user recreates a segmentation of the prostate and applies the registrations. The user is satisfied with the result and approves it. 

Now my question: Should the approved prostate segmentation label and the approved targets be used in subsequent needle images afterwards or should SliceTracker still use the Cover Prostate segmentation and targets?

**Comment by fedorov** [comment]
I believe cover prostate segmentation targets and segmentation should be used.

When needle registration fails, this probably means there was too much motion. So let's say needle image _N_ failed. Then we do manual segmentation, this helps with registration initialization, and we re-register CoverProstate to _N_. Assuming manual segmentation leads to a successful registration, when we register the needle image _N+1_, rigid transform from _N_ registration will be used to initialize registration of CoverProstate to _N+1_, and if the new registration is successful, the targets associated with CoverProstate will be propagated with the registration in that step.

Hopefully this makes sense!

**Comment by che85** [comment]
Ok yes that makes sense and also is currently used like that. The most recent approved rigid transformation is used for needle images.

**Comment by fedorov** [comment]
Just to mention the justification - the idea is that CoverProstate has better resolution, so registration problem is easier, and also if we "chain" registrations of the needle images, we will have error accumulation.

**Comment by che85** [comment]
Yes I already thought so. I just wanted to clarify it to check if the way I implemented it is correct. ;)
