### ISSUE TITLE
Integrate Slicer3 z-frame registration code into the module

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#120]
Need to dig the code here https://github.com/SlicerProstate/ProstateNav

and see what is needed and how it can be abstracted to use Slicer3 z-frame code

**Comment by fedorov** [comment]
Use SlicerProstate extension as an example of how to add CLI modules to the extension https://github.com/SlicerProstate/SlicerProstate (e.g., DWModeling is a CLI, and DistanceBasedRegistration is a scripted python module)

**Comment by che85** [comment]
See https://github.com/SlicerProstate/ZFrameCalibration for the actual implementation

**Comment by fedorov** [comment]
> See https://github.com/SlicerProstate/ZFrameCalibration for the actual implementation

We need to re-organize SliceTracker as an extension with SliceTracker and ZFrameCalibration modules. I think it is possible to add ZFrameCalibration to the repository while preserving the commit history.

**Comment by fedorov** [comment]
See this guide for integrating code from one repository into another while preserving commit history: http://nuclearsquid.com/writings/subtree-merging-and-you/
