### ISSUE TITLE
IncomingDataMessageBox should remember pushed button in case of "Do not notify again"

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#121]
- This very useful when the user wants to prevent showing that messagebox in targeting step and pushing "Track Targets".
-- The next time, image data is received and SliceTracker is not in evaluation step, it would remember the answer when checking "Do not notify again". --> Registration of subsequent needle images will be executed automatically.

**Comment by fedorov** [comment]
:+1: 

One comment is perhaps instead of "Do not notify again" it should be more explicit and say "Remember the selection and do not notify again" ?

**Comment by che85** [comment]
Yes I agree
