### ISSUE TITLE
Provide config file for defining settings e.g. zFrame calibration algorithm to be used

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#126]
- default values should be provided

@fedorov should we define a constant in the code for the default config file and provide a file selector for changing it?

**Comment by fedorov** [comment]
Let's use config file and open source as default

**Comment by che85** [comment]
@fedorov What else should we store in a configuration file? 

I created a wiki page for this information.
https://github.com/SlicerProstate/SliceTracker/wiki/Configuration-File
