### ISSUE TITLE
Case specific file structure for avoiding need of user action for selecting preop,intraop and output directory

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#127]
Two possible actions:
a) Create a new case
b) Open existing case

Current file structures that is used for AMIGO prostate biopsy cases:
```
└── Case###-YYYYMMDD
    ├── DICOM
    │   └── Preop
    │   └── Intraop
    ├── RegistrationScene
    ├── IntraopScene
``` 

Proposed file structure for SliceTracker cases:
```
└── Case###-YYYYMMDD
    ├── DICOM
    │   └── Preop
    │   └── Intraop
    ├── mpReviewPreprocessed
    │   └── ...
    ├── SliceTrackerOutput
``` 

a) User creates new case and needs to select mpReviewPreprocessed directory. DICOM and Preop directory are expected to exist already. Intraop will be created (if not already exists). Slicer storescp is started for intra procedural images. As soon as image data arrives in DICOMDatabase, the images are copied to the intraop directory within SliceTracker specific file structure.

b) Loading a old case expects the introduced file structure and gives feedback if there is something wrong with the selected one. Other than that, mpReviewPreprocessed and intraop data is loaded.

Therefore we should not provide any possibility to change the directories in order to make sure, that the data also can get loaded later. 

In case that the case has to be reloaded during prostate biopsy, there should be some kind of sync between intraop directory to make sure if there are no series missing in both intraop directory and DICOMDatabase

@fedorov What do you think about that?

**Comment by fedorov** [comment]
as discussed, this sounds good

**Comment by fedorov** [comment]
I thought more after the discussion today, and I think the proposal for the file structure discussed above (and repeated below) makes sense. Let's not change it. With the updates to DICOMListener, let's save incoming files into ```DICOM/Preop``` and ```DICOM/Intraop```, and NOT copy DICOM files to mpReviewPreprocessed directory.

```
└── Case###-YYYYMMDD
    ├── DICOM
    │   └── Preop
    │   └── Intraop
    ├── mpReviewPreprocessed
    │   └── ...
    ├── SliceTrackerOutput
```

**Comment by che85** [comment]
So we are going to execute mpReviewPreprocessor without organizing DICOM, correct?

**Comment by fedorov** [comment]
Yes. 

I just don't want to create tasks that are not justified. Let's have the main goal achieved, which is being able to support the case. We have all the information captured (I think!) so it hopefully can be re-arranged in any way as needed later, if there is a real need.
