### ISSUE TITLE
Fiducial glyph type

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#128]
I think that the glyph we use in Slicer3 for fiducials may be better (more prominent) than the one used in SliceTracker right now (see below).

![image](https://cloud.githubusercontent.com/assets/313942/13931818/7a3dfb7c-ef7b-11e5-8068-52396e297e3c.png)

This is controlled by GlyphType in ```Markups > Display Properties```, the first one is Sphere3D and the bottom one is StarBurst2D. 

![image](https://cloud.githubusercontent.com/assets/313942/13931867/b45ebd1e-ef7b-11e5-8167-2efe6f1b734f.png)

@che85 which one do you like better?

**Comment by che85** [comment]
Both are fine for me. if you prefer the "old" one, I am fine with it.

**Comment by fedorov** [comment]
Ok, let's change it to the StarBurst2D to be consistent with Slicer3, and I also think it is more prominently visible.
