### ISSUE TITLE
Full impementation of workflow as is in current AMIGO prostate biopsy cases including mpReview and Slicetracker

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#129]
1. Starting new Case
  1. System creates directory structure and starts storescp for receiving Preop image data
  2. Once Preop data has been received, mpReviewPreprocessor is executed and mpReviewPreprocessed directory is created
  3. Switching to mpReview
2. User creates Segmentation(s) and sets target(s)
3. Case completion
  4. Switching back to SliceTracker
  5. Starting storescp for receiving Intraop image data
... following workflow as currently is.

TODO: We need to think about loading an existing case.

**Comment by fedorov** [comment]
@che85 wrote
```
Regarding the Preop data:
I only start the storescp process without including it into the DICOMDatabase. 
THen running mpReviewPreocessor, deleting "old" preop directory and using 
mpReview.... and so on. After mpReview is finished I set Slicetrtacker preop 
directory to mpReviewPreprocessed dir. Intraop storescp also only runs storescp 
process without importing it immeadiately. Importing the DICOM data is handled 
afterwards by watching the intraop directory (as it currently is implemented)
THis way we have better control over importing to DICOMDatabase
DICOMListener doesn't provide receiving only without importing but I am going to 
inherit from DICOMProcess and adapt it to out pupose.
```

**Comment by fedorov** [comment]
Why not do it the other way:

1. Create temporary DICOM DB
2. use DICOMListener as is, importing all incoming files into an empty directory
3. Modify mpReviewPreprocessor to add a function that takes on input no a directory with DICOM files, but DICOM DB
4. Iterate over the series for the patient in DICOM DB, for each series iterate over instances, look up the file for each instance, copy that file to the DICOM directory, and run the plugin to get the volume

This way the changes are quite minimal, and all are on the mpReview side

**Comment by fedorov** [comment]
why not modify Slicer DICOMListener to make file indexing optional? In this situation it is very easy to avoid code duplication.

**Comment by fedorov** [comment]
for the reference: http://slicer-devel.65872.n3.nabble.com/DICOMListener-with-optional-Indexing-td4036422.html

**Comment by che85** [comment]
I still propose to have two buttons next to each other one for creating a new case and another for opening a case. It's common, that all cases somehow are saved under one root directory like ClinicalCases, so I also propose to have a root directory which can be changed by the user (using a directory button or with in our config file).

When creating a new case, Slicetracker logic identifies the next CaseNumber from the root directory by parsing it. So if the highest case number in that root directory is Case377-20160321, then the next (newly created directory) will be Case378-YYYYMMDD with YYYYMMDD describing today's date.

When pushing Open Case, a directory selection widget opens with root directory ClinicalCases to select a Case

@fedorov  What do you think?

**Comment by fedorov** [comment]
Yes, I like your proposal a lot!
