### ISSUE TITLE
Load/continue case (important when unexpected behavior or crash happened)

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#132]
We should provide the possibility to load and continue (if not completed) cases. 

I propose to save a json or xml file in the output directory which mirrors the registration results including the saved file names.

I can also imagine that several runs has been made on the same case which would result in different output directories below SliceTrackerOutputs. The user should be notified about that and be able to choose the run that should be opened.

In order to see if a run was completed, we should add a file .completed or save it in the xml or json file.

**Comment by che85** [comment]
@fedorov What do you think about that?

**Comment by fedorov** [comment]
This sounds good, but I am afraid this may be overly complicated. Would be nice if the internal data structures could be mapped directly to this xml/json file. Did you think to implement it that way?

**Comment by che85** [comment]
Yes kind of. I need to take a look into this, but I think it would be too much effort.

**Comment by fedorov** [comment]
> I think it would be too much effort

what would be too much effort?

**Comment by che85** [comment]
Oh typo. I meant to say that it would not be too much effort.

**Comment by che85** [comment]
Seems like we don't save the moving nor the fixed label. In order to be able to restore data completely we should do that as well.

**Comment by fedorov** [comment]
Hm, according to this document, we do! https://github.com/SlicerProstate/SliceTracker/wiki/Document-file-names-and-conventions-used-for-saving-results

**Comment by che85** [comment]
Only the Cover Prostate Label yes....

**Comment by che85** [comment]
I Identified the following useCases when continue should be possible:
- After Case directory creation without receiving any data
- After receiving preop (mpReviewpreprocessed not filled):
  - mpReviewPreprocessing should be started
- After mpReviewPreprocessed:
- After Intraop received with mpReviewPreprocessed data
- After Intraop received without preop
- After registration(s) has been done

**Comment by che85** [comment]
"New Case" button should prompt user when currently running a session if the current session can be closed and then create a new directory. Same for opening a case/session
