### ISSUE TITLE
ZFrame Registration failed with current assumptions 

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#134]
Current assumptions:
- setting center point and upper right corner
- start = center point slice - 4 slices
- end = center point slice + 4 slices

Creating label, masking image and selecting start=5 and end=10 works as expected

Slicertracker makes following assumptions: start=6 end=14 where not all fiducials are visible on all slices

**Comment by che85** [comment]
I propose that the user needs to click into center, upper right and then has to click onto start and end slice. Another way would be to have those spin boxes like it is already implemented in ZFrameCalibration module

**Comment by fedorov** [comment]
I think center is sufficient to initialize the ROI of fixed size, and then maybe give a popup message to the user with the instructions and adjust the extent in the sagittal view?

In the future, we can attempt more robust ROI initialization. One very easy approach that might work is to run Otsu thresholding inside the cropped square region, and count the islands. It will still need to be checked and confirmed by the user. But this is for the future! :)

**Comment by che85** [comment]
@fedorov: Maybe we can keep my assumptions and provide a button "Retry with setting exact ROI extent" or something similar? In Most cases so far my assumptions worked just fine.

**Comment by fedorov** [comment]
sure, that is fine too

**Comment by che85** [comment]
@fedorov: the otsu approach works perfectly so far. As a fallback I could add a checkbox and two spin boxes to enable setting start and end index manually by the user. That would save time instead of expecting the user to adjust the ROI, where I think it could be difficult for untrained users.
