### ISSUE TITLE
Switching layouts in evaluation step should enable/disable crosshair automatically

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#136]
Switching to FourUp: enable crossshair
Switching to SideBySide: disable crosshair

**Comment by fedorov** [comment]
I would also have a button in the module panel to switch this as needed

**Comment by che85** [comment]
The button already exists. I meant to say, that it should be enabled by default when switching to FourUp.

![image](https://cloud.githubusercontent.com/assets/10195822/14508467/8fb7434c-0195-11e6-851e-b4affaec8744.png)

**Comment by fedorov** [comment]
Makes sense, agreed
