### ISSUE TITLE
All series that come from the scanner should be loaded

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#139]
Actions (skip/track) and their automatic applications should be defined only for the recognized series, but any series received from the scanner should be in the scene in case operator needs to display it.

**Comment by che85** [comment]
This also affects the current handling of importing DICOM series into Slicer and handling them (including colors) in the intraop series selector.

**Comment by che85** [comment]
Should not be too much effort, but might take some time to handle this properly.

**Comment by che85** [comment]
What also is affected: IncomingDataReceive message etc. 

I will think about it and will adapt everything to this use case

**Comment by fedorov** [comment]
When you come up with the plan, can you first describe it here before implementing?

**Comment by che85** [comment]
Actually I am just importing all incoming DICOM series, then all new series are checked for the same PatientID. Tracking Targets will only be enabled if the DICOM series is eligible for tracking (Cover Prostate, Guidance, Cover Template) and some more specific requirements like: Cover Prostate is eligible if ZFrame Registration hasn't been done yet and no Cover prostate approved registration result is available.

Series that are note eligible are only available to be previewed in red slice view

**Comment by fedorov** [comment]
> Series that are note eligible are only available to be previewed in red slice view

Are they going to be visible in the series selector?

**Comment by che85** [comment]
Yes.

**Comment by fedorov** [comment]
👍
