### ISSUE TITLE
Support w/l modification of the Fg layer

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#140]
Suggested approach:

1) add button to switch to w/l mode (if not hard, change the mouse icon when changed)
2) depending on the transparency setting, round the transparency to either 0 or 1
3) modify w/l for either Fg or Bg depending on the transparency setting
4) user has to explicitly turn off w/l mode

**Comment by che85** [comment]
Tool should be disabled when Flickering or Rock mode is active
