### ISSUE TITLE
Handling the situation when registration fails

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#153]
if all registrations completely fail, notify user.

**Comment by che85** [comment]
@fedorov Do you have any idea how to test that easily?

**Comment by fedorov** [comment]
You mean the failure of registration ? Does it create a volume when it fails?

**Comment by che85** [comment]
Yeah. I guess it creates an empty volume. Maybe I can just create one.

**Comment by fedorov** [comment]
If registration fails and no volume has been created, the last registration stage that produced a volume should be selected.

**Comment by fedorov** [comment]
Also related to #170
