### ISSUE TITLE
Display significant changes of computed hole in target table

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#158]
When significant changes has been detected in comparison to CoverProstate, then this should be colored

**Comment by fedorov** [comment]
Define "significant"?

**Comment by che85** [comment]
Ok let's say "as soon as it changes".

**Comment by che85** [comment]
@fedorov Do we also want to store the computed hole and depth for each target for approved registrations? I don't know if this could be useful for the future...

**Comment by che85** [comment]
I implemented it the following way:
![image](https://cloud.githubusercontent.com/assets/10195822/16098916/6bd3ea88-3323-11e6-9198-c5a356b798db.png)

or 

![image](https://cloud.githubusercontent.com/assets/10195822/16099520/a58d0be4-3326-11e6-804d-5d4bb79294b6.png)

**Comment by che85** [comment]
Cover Prostate depth would be displayed as a tooltip when hovering over the cell

![image](https://cloud.githubusercontent.com/assets/10195822/16104309/0622aeec-334e-11e6-90e5-5763e70027f4.png)

**Comment by fedorov** [comment]
Very nice. I would also suggest to highlight the depth in the same way if that changes more then some threshold, maybe more than 5 mm?

**Comment by fedorov** [comment]
> Do we also want to store the computed hole and depth for each target for approved registrations? I don't know if this could be useful for the future... 

yes, I think saving this will not hurt, but might be useful

**Comment by che85** [comment]
Yeah i also thought about a threshold of 5 mm. 

And I am going to store the computed hole and depth for approved targets.

If targets are moved, how would we store the hole and depth then?

**Comment by fedorov** [comment]
If the user moves the targets, hole/depth should be updated, and we are already saving whether user modification was made or not, right?

**Comment by che85** [comment]
Yes exactly.
