### ISSUE TITLE
Cover Prostate registration should not be skippable/rejected

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#160]
Cover Prostate registration must not be skippable/rejectable in case that there won't be received a new Cover Prostate. The user could not do anything more since an approved Cover Prostate is needed for further registrations. 

Is that the case, I would suggest, that the user can evaluate again in order to be able to change the current situation. 

In a nutshell: skipping/rejecting of the Cover Prostate without receiving another Cover Prostate would cause the case not be "frozen" since the user cannot do anything else than viewing following images.

So we probably have 2 possible options:
1) User must not be allowed to skip or reject Cover Prostate registration
2) If user is allowed to skip/reject Cover Prostate registration, the user should be allowed to revaluate Cover Prostate in case that there won't be received a new one. 

I don't see other options right now. 

@fedorov Any thoughts?

**Comment by fedorov** [comment]
Can you clarify - are you talking about registering CoverProstate to subsequent needle image, or planning image to CoverProstate?

**Comment by che85** [comment]
I was talking about the registration from planning image to CoverProstate

**Comment by fedorov** [comment]
In this case, I think it should not be mandatory. We did have situations when we didn't have the planning image at all, targets were placed on the cover prostate image, and then the module was used to compute the insertion plan and assist in tracking.
