### ISSUE TITLE
Revisit default configuration handling

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#162]
It would be more consistent if the default configuration in https://github.com/SlicerProstate/SliceTracker/blob/master/Resources/default.cfg was used to initialize the SliceTracker section in genral Slicer configuration.

**Comment by che85** [comment]
How would you do that? Any examples?

**Comment by fedorov** [comment]
I was thinking that we could have a settings initializer function that for each settings saved in the default configuration checks if they exist under SliceTracker module in Slicer app settings (using these functions: https://github.com/SlicerProstate/SlicerProstate/blob/master/SlicerProstate/SlicerProstateUtils/mixins.py#L65-L74), and if not - adds these settings to Slicer app settings. Later on, the application accesses the settings only using those get/set functions.

**Comment by che85** [comment]
@fedorov I implemented it the way that it always reads the configuration file when initializing SliceTracker and instead of first checking for existing Slicer settings just overwrites them for the module. 

>I was thinking that we could have a settings initializer function that for each settings saved in the default configuration checks if they exist under SliceTracker module in Slicer app settings (using these functions ... and if not - adds these settings to Slicer app settings.

The way you described it, would not take into account a change of the configuration settings

**Comment by fedorov** [comment]
As discussed, the default config file should only be used for the first time the module is started, or in cases when somehow the settings in Slicer.ini disappeared. In other cases, the settings from Slicer.ini should be used.

@che85 will revise #164 to address this.
