### ISSUE TITLE
Documentation gitbook

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#167]
There should be basic documentation on gitbook on how to use the module for Soichiro

**Comment by fedorov** [comment]
of note, z-frame registration only works for 512x512 image resolution

**Comment by fedorov** [comment]
Somewhat relevant guide that describes some of the components expected in a user guide and structure: http://www.klariti.com/technical-writing/User-Guides-Tutorial.shtml

@che85 if you have examples of documentation for similar tools, or similar guides - please add here!

**Comment by fedorov** [comment]
gitbook docs: https://toolchain.gitbook.com/

**Comment by fedorov** [comment]
initial pre-release documentation https://www.gitbook.com/book/fedorov/slicetracker/details

read view: https://fedorov.gitbooks.io/slicetracker/content/

**Comment by fedorov** [comment]
@lassoan FYI, if you have comments, please let us know. I include you, since we talked about documentation in the context of gitbook at the project week. Let me know if you would like me to add you as a collaborator to the gitbook project, otherwise feel free to comment. Christian and I are working on the initial version of the documentation for this module to pass to the users for training. We have not shared it with users yet.

**Comment by fedorov** [comment]
@PeterBehringer @pieper @jcfr FYI as well...

**Comment by PeterBehringer** [comment]
this is nice! will the user guide be linked here: "For more details, please read SliceTracker user guide." once you finished it?

**Comment by fedorov** [comment]
@PeterBehringer defnitely, I was just unsure what would be the final url. I wanted to get a free plan for the SlicerProstate organization on gitbooks, but didn't get a response from their support.

**Comment by fedorov** [comment]
documentation development moved to gitbook branch https://github.com/SlicerProstate/SliceTracker/tree/gitbook

**Comment by fedorov** [comment]
on gitbook, ownership transferred to SlicerProstate organization

new home: https://www.gitbook.com/book/slicerprostate/slicetracker/details
