### ISSUE TITLE
While receiving incoming data, no progress popup shows up

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#176]

**Comment by che85** [comment]
@fedorov Where would you like to see a popup? I don't think that for instance it would be a good idea to show a popup while segmenting or evaluating.

The only step I could imagine is the overview step.

Other than that it would be nice to be able to have a progressbar on the bottom of slicer where anyway status updates are displayed.

**Comment by fedorov** [comment]
My main concern is that there is no popup when I see the spinning ball, so it is not clear whether Slicer froze/about to crash, or it is busy doing something. If possible, it would be nice in those cases when the main gui is not responsive to explicitly communicate to the user that it is busy and busy with what.
