### ISSUE TITLE
When saving results, overwrite existing files

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#177]
While testing I figured out, that SliceTracker does not overwrite files in the output directory.

**Comment by che85** [comment]
@fedorov Saving should only be executed for the currently evaluated image. Otherwise the more images has been evaluated, the more will be saved which leads to consume more time while saving. What do you think?

**Comment by fedorov** [comment]
I agree, makes sense to save only the latest results, and replace the top-level json. I can't think of a situation where we would need to re-save previous results.
