### ISSUE TITLE
Need to display to the user which files have been saved?

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#178]
This is pretty disturbing when a long case has been completed and the user pushes "Case completed". Right now SliceTracker displays a popup that shows all saved filenames.

In my opinion we should just say something like "Case successfully completed and saved"

@fedorov What do you think?

**Comment by che85** [comment]
I think it would be enough to log that for developers

**Comment by fedorov** [comment]
Agreed
