### ISSUE TITLE
Having more targets causes SliceTracker to slow down

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#192]
Caused by cursor/target distance computation which is displayed in the target table.

I need to think about improving that. Otherwise we should provide an option to disable it in the UI

**Comment by fedorov** [comment]
Considering this operation is not really needed to be performe dinteractively, we could just calculate distances on a key press. What do you think?

**Comment by fedorov** [comment]
I mean keyboard key

**Comment by che85** [comment]
Yeah we can consider doing that or a button? Otherwise we could also somehow cancel processing the event, when already a new one got fired. I guess the continuous movement of the cursor adds up the computation...

Another option would be to store the computed values. As far as I know, QAbstractTableModel retrieves pretty often data so each time the distance is computed again.

**Comment by fedorov** [comment]
> Yeah we can consider doing that or a button? Otherwise we could also somehow cancel processing the event, when already a new one got fired. I guess the continuous movement of the cursor adds up the computation...

not sure how we can do a button, if we need the distance at the location of the mouse pointer. are there qt constraints that prevent implementation of a keyboard key press?

**Comment by che85** [comment]
I already improved it a lot by avoiding the computation of the ZFrame hole and depth everytime data is requested from the qt table for displaying. 

I also thought about that we might only compute the distance for the selected target. What do you think about that?

This would minimize computation time and confusion for the user when there are many targets.

**Comment by che85** [comment]
@fedorov I think it makes sense to only compute the distance for the currently selected target. Anyway the radiologist selects only one target at a time. Everything else would be distracting

**Comment by fedorov** [comment]
If that will speed things up, sure. I agree this makes sense inost cases. Still curious - why not key press?

**Comment by che85** [comment]
Yeah maybe keypress would be good. Which key would you expect it to be?

**Comment by fedorov** [comment]
d for distance?

**Comment by che85** [comment]
I am going to close this issue since we anyway don't show the distance for several targets anymore. 

related to #266
