### ISSUE TITLE
Factor out WindowLevelEffect into separate widget for reusability reasons

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#208]

**Comment by che85** [comment]
@fedorov Should that be a callable module, what can be called in Slicer?

Which functionality do you expect?
- The current class only supports mouseclick and dragging events, NOT this rectangle drawing...

**Comment by fedorov** [comment]
> Should that be a callable module, what can be called in Slicer?

whatever is easier

> The current class only supports mouseclick and dragging events, NOT this rectangle drawing...

This is fine, we won't need the rectangle until we start working with the DCE parametric maps again.

**Comment by che85** [comment]
@fedorov Should it be moved to SlicerProstate then or where do you want it to be placed?

**Comment by che85** [comment]
@fedorov I already extracted a class which provides no widget. Do you want a widget with just a button or what would you like to have?

**Comment by fedorov** [comment]
yes,  think SlicerProstate util makes sense, since that is a dependency of both SliceTracker and mpReview.

About widget - I thought there are other classes in SlicerProstate util that correspond to some of the buttons in SliceTracker - is this correct?

**Comment by che85** [comment]
No the buttons in SliceTracker are all coded in Slicetracker. Some components like the CustomStatusProgressbar, some message boxes, the watchbox ... are implemented in SlicerProstate and included in SliceTracker

**Comment by fedorov** [comment]
ok

I am not sure, since I have not touched either mpReview or especially SliceTracker in a very long time.... Whatever makes more sense to you!

**Comment by che85** [comment]
Ok I am going to create a class which is inherited from qt.QButton that can easily added to anyone's UI.
