### ISSUE TITLE
Bias Correction shall be done if endorectal coil was used

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#21]
Since the functionality for creating bias correction does not exist in PCampReview, the user is prompted to answer if an endorectal coil was used. If so, an bias correction is directly done after selection of preop data directory in PCampReview style

**Comment by che85** [comment]
fixed

**Comment by fedorov** [comment]
@che85 just wanted to let you know that I am not getting automatic notifications when you reference an issue from commit, only when there is a new message. If you would like to get my input, please add a message to the issue after you commit, or another way to do it is to issue a pull request that references the issue - I will get a notification about the pull request. What do you think?
