### ISSUE TITLE
Change slice annotations in registration evaluation step

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#212]
from "old" to "pre-needle"
from "new" to "post-needle"

**Comment by fedorov** [comment]
did Kemal requested this? I thought he specifically liked "old/new"

**Comment by che85** [comment]
No, but in the meeting with Ron we agreed to that change as far as I remember

**Comment by che85** [comment]
As discussed with @fedorov: we will need to talk to Kemal about that to make sure that he agrees with that change and get his opinion if it would improve the annotations.

**Comment by che85** [comment]
I am closing this issue since it was never discussed and our radiologist actually proposed the current names to use.
