### ISSUE TITLE
Data Management for multiple needle confirmation images

### ISSUE THREAD

**Issue by PeterBehringer** [SlicerProstate/SliceTracker#22]
@che85 lets talk about this today

**Comment by PeterBehringer** [comment]
@fedorov @che85 do you guys already thought about organisation of output? What I mean is, how subsequent volumes (for rigid, affine & bspline) as well as targets should be named for any specific needle image.

**Comment by fedorov** [comment]
Let's save all in one directory for now, and document the naming conventions used in this issue.

**Comment by che85** [comment]
see issue #4 for further comments
