### ISSUE TITLE
[Retry segmentation step] add button for going back to registration evaluation step

### ISSUE THREAD

**Issue by leochan2009** [SlicerProstate/SliceTracker#236]
During the segmentation in the retry registration, it would be nice to have a button to abandon the current segmentation and go back to the previous "retry accept, reject" panel.

Thanks,
Longquan

**Comment by che85** [comment]
That makes sense to me. Especially in the case that (like @leochan2009) explained to me, where the user wants to retry the segmentation but in the meanwhile a new needle image has been received.

@fedorov What are your thoughts about this? I would only implement this button for the "retry" step

**Comment by fedorov** [comment]
Makes sense to me, I can see how this can be useful

**Comment by che85** [comment]
This issue was fixed in #270
