### ISSUE TITLE
Check for VolumeClip module existence

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#25]
Since SliceTracker is dependent to VolumeClip extension

**Comment by fedorov** [comment]
the dependency is already specified - is it correct, or does it not change any behavior?

https://github.com/SlicerProstate/SliceTracker/blob/master/RegistrationModule/RegistrationModule.py#L25

**Comment by che85** [comment]
Well yes that's true but the module does not even appear in the dropdown for module selection when those dependencies are not met. 

The user could only know what's going on by going to the log messages... 
"When loading module  "RegistrationModule" , the dependency "VolumeClipWithModel" failed to be loaded. "

A much more "user friendly" approach would be to check this while loading the module and giving direct feedback to the user.

**Comment by fedorov** [comment]
Oh, I see - I guess it is this way because SliceTracker is not a proper extension. If it was, this issue would be handled by the ExtensionManager, I think. I agree at this moment what you propose is the best approach.

**Comment by che85** [comment]
fixed with pull request #32
