### ISSUE TITLE
Integrate deep learning for prostate gland segmentation into the workflow

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#251]
- [x] Deep learning should be saved in configuration

**Comment by che85** [comment]
@mehrtash basically I only need to use https://github.com/mehrtash/Prostate-Segmenter, right?

**Comment by che85** [comment]
@fedorov Until when should that be integrated?

**Comment by che85** [comment]
fixed in https://github.com/SlicerProstate/SliceTracker/pull/270
