### ISSUE TITLE
After moving target in evaluation step use that one for further registrations

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#252]
This is not the case right now.

Even when targets are moved, the CoverProstate target(s) will be used for further registrations

**Comment by che85** [comment]
After thinking about this issue I remembered that we agreed to using modified target only if those were modified in CoverProstate registration.

**Comment by fedorov** [comment]
Yes, this makes sense, since we always register cover prostate to needle confirmation images.
