### ISSUE TITLE
Make VolumeClip a SegmentEditor effect

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#255]

**Comment by lassoan** [comment]
I have added a scripted segment editor effect template to the Slicer extension wizard. It will be available in tomorrow's build.

**Comment by fedorov** [comment]
@Kmacneil0102 let this be your next task!

Here's the background:

VolumeClip is a nice extension that allows to perform segmentation by approximating volume surface from the fiducial points placed by the user. Unfortunately, this functionality is currently not integrated with the Segment Editor. Once this task is completed, it will be possible (eventually, after mpReview is updated to use Segment Editor) to use the same segmentation tool both for segmenting pre-procedural and intra-procedural data in SliceTracker.

Your task would be to add VolumeClip functionality as a new effect to SegmentEditor. Since you are at Queen's, this is a perfect opportunity, since you can perhaps ask Andras for SegmentEditor help if you are stuck. How does this sound?

**Comment by Kmacneil0102** [comment]
Sounds great! I've done some background on Segment Editor and Volume Clip and taken a look at the template Andras mentioned before commenting here, and think I have what I need to get started.

**Comment by fedorov** [comment]
@Kmacneil0102 did you get a chance to connect with @lassoan to discuss this task?

**Comment by lassoan** [comment]
Yes, we've talked about how to implement this effect yesterday.

**Comment by che85** [comment]
related to https://github.com/SlicerProstate/mpReview/issues/93
