### ISSUE TITLE
TODOs for the refactored SliceTracker

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#257]
- [x] Handle situation when multiple CoverTemplates are received
- [x] approving, rejecting, skipping of the most recent or earlier series always skips the (n) previous series that has not been processed.
- [x] Target visibility of retries in FourUp layout:
  - [x] Registered targets are also visible in Biopsy plan
- [x] Registration evaluation buttons icons
- [x] Handling of reception of image data from patient other than the current one.
- [x] Skipping should be confirmed
- [x] Setting targets in non preop mode:
  - [x] Computation of whole and depth immediately
  - [x] Controlling visibility of tables in case of retryMode
  - [x] Add Annotation when targeting is active 
- [x] Prevent methods connected to layout changes if selected module is not SliceTracker
- [x] Handling of availability of layout buttons for different steps
- [x] Memorize target selection for target table
- [x] Non preop mode: Setting targets on CoverProstate should result in immediate display of template grid hole and depth calculation for all targets
- [x] BUG: Each save also adds a new caseClosed item to the metafile
- [x] Handling Annotations of registration results when CoverProstate without preop is selected

**Comment by fedorov** [comment]
I was using mpReview standalone, and ran into this error below. I don't know what is the cause, but it should be tested that mpReview can be used independently of SliceTracker.

![image](https://cloud.githubusercontent.com/assets/313942/24210534/d4617792-0eff-11e7-9c99-bc089a61ddf6.png)

**Comment by che85** [comment]
Will be fixed in the refactored version

**Comment by che85** [comment]
I modified the case specific buttons, made Watchbox attribute title bold and added capability to display attributes next to each other in n columns
![image](https://cloud.githubusercontent.com/assets/10195822/24271060/1dec0442-0fee-11e7-9e93-16be8438bde8.png)

**Comment by fedorov** [comment]
I love it!

**Comment by che85** [comment]
@fedorov Maybe we should also consider getting rid of the completion button and instead prompting the user when the close button is clicked and ask if the case is completed..

What do you think?

**Comment by fedorov** [comment]
Yes, makes sense. Should we also prompt in the situation when the user attempts to switch to another module?

**Comment by che85** [comment]
We could say when it switches to other modules other than mpReview or the new Pirads. But I would leave this open for the future. When Slicer closes, the user will get prompted anyway.

**Comment by fedorov** [comment]
- [ ] add capability to check network connectivity: start storescp, receive data, confirm to user connection ok, ignore data
