### ISSUE TITLE
Add capability to change series type for selected series

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#258]
It might happen, that images coming from the scanner don't have expected naming or have been renamed by mistake.

That's why we need to add a button that once pushed displays a popup showing a dropdown with all available (known) series types:

* "COVER PROSTATE"
* "COVER TEMPLATE"
* "GUIDANCE"
* "VIBE"
* "Other"

TODO:
  - [x] create predefined list of series types
  - [x] find icon for edit/modify series type
  - [x] adapt meta output with collected information
- [x] add a button (edit icon) next to the intraop series selector which will upon click popup a list with available series types.
- [x] style all that in a proper way and highlight information to the user in an appropriate manner (tooltip)

**Comment by che85** [comment]
@fedorov I guess you meant this issue, right?

Is this a complete list of assignable series types or do you have any suggestions or other ideas?

**Comment by fedorov** [comment]
yes, right - in the other issue, I thought that button was intended to allow selection of the series type

**Comment by fedorov** [comment]
and I cannot find the other issue quickly to link here

**Comment by che85** [comment]
it's https://github.com/SlicerProstate/SliceTracker/issues/260

**Comment by che85** [comment]
Ok so I propose to do the following:
* predefined list of possible series types
* series gets assigned to a specific type automatically (default)
* can be overriden by the operator

TODO:
  - [ ] create predefined list of series types
  - [ ] find icon for edit/modify series type
  - [ ] add a button (edit icon) next to the intraop series selector which will upon click popup a list with available series types.
  - [ ] style all that in a proper way and highlight information to the user in an appropriate manner (tooltip)

**Comment by fedorov** [comment]
sounds great!

**Comment by che85** [comment]
looks like the following now:

![image](https://cloud.githubusercontent.com/assets/10195822/26138805/b2ec84c4-3a99-11e7-8eb8-2573cf4a7b69.png)

**Comment by che85** [comment]
Ok I changed it again to have a menu popup:

TODO: add icon
![image](https://cloud.githubusercontent.com/assets/10195822/26164839/efb08330-3afb-11e7-82c6-bb71b6522098.png)

**Comment by fedorov** [comment]
Looks fine to me. Is it difficult to get rid of the white space in the popup?

Also, I think it might be good to always request confirmation from the user when they want to change the image type, since this will have significant impact on the workflow, and we don't want this change to happen by accident. What do you think?

**Comment by che85** [comment]
I will try to get rid of the white space. 

Upon selection of a seriesType different from the current one we can prompt the user for confirmation. Makes sense to me.

**Comment by che85** [comment]
Also it's important that the operator should not be allowed to change the series type in all situations that you can imagine. Only series that don't have a registration result should be reassignable. 

Taking into account that we have a series selector as shown in the screenshot below, the operator could assign any series type to any series could totally mess up the workflow. Let's say the series types were changed to Guidance, Guidance, CoverProstate, CoverTemplate

Giving more freedom always gives more room for failures in undefined states

![image](https://cloud.githubusercontent.com/assets/10195822/26171227/2ee6c79c-3b12-11e7-95b7-35423ee5f993.png)

**Comment by fedorov** [comment]
Yes, definitely. Series that have already been processed imply that the assigned image type has been approved by the operator.

**Comment by che85** [comment]
We should also add some indicator signalizing that the series type has been changed for the currently selected series (not automatically assigned series type)

**Comment by che85** [comment]
I am already displaying the series type within the tooltip, but that's not enough because it's not visual at anytime.

**Comment by che85** [comment]
If the assigned type differs from the original series type, the icon changes to an "info" icon and the following tooltip will be displayed upon mouse hovering

![image](https://cloud.githubusercontent.com/assets/10195822/26175342/6316c0c2-3b20-11e7-9622-c222839a12ee.png)

**Comment by fedorov** [comment]
Is this really needed? The main use case I think the manual override should address is when the series description does not match any of the known rules. It is not important to know what was the original assigned series type. Can you explain your thoughts to add this?

**Comment by che85** [comment]
Let's say the user changes the series type from Cover Prostate to Guidance and wonders afterwards why the tracking button is disabled (caused because no Cover Prostate was successfully registered). The user gets direct feedback about what was changed (just as a reminder)
