### ISSUE TITLE
Add icons in overview step for tracking and skipping series

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#260]

**Comment by che85** [comment]
looks like this now:

![image](https://cloud.githubusercontent.com/assets/10195822/25969784/2a3454e2-3664-11e7-85f9-693b05cdcd7e.png)

**Comment by fedorov** [comment]
Does the icon on the right of the green bar indicate the type of the series? If yes - what are the other options, and what happens when you click that button?

**Comment by che85** [comment]
No the right one indicates skipping

**Comment by che85** [comment]
![image](https://cloud.githubusercontent.com/assets/10195822/25971784/8660c050-366b-11e7-826b-2eaaf759bac6.png)
left one: tracking
right one: skipping
