### ISSUE TITLE
Implement Slicelet

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#261]

**Comment by che85** [comment]
## **That's how the Slicelet looks like:**
<img width="1920" alt="screen shot 2017-04-21 at 3 33 10 pm" src="https://cloud.githubusercontent.com/assets/10195822/25293228/e294ea14-26a7-11e7-8440-7f16bc0844a1.png">

## **Hideable module panel (double-clicking or drag splitter to the left side**
<img width="1920" alt="screen shot 2017-04-21 at 3 33 15 pm" src="https://cloud.githubusercontent.com/assets/10195822/25293229/e29e76ec-26a7-11e7-9595-128a61510fa3.png">

**Comment by fedorov** [comment]
Very nice!
