### ISSUE TITLE
Add more information about the color coding of the intraopSeriesSelector

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#267]
It would be great to have some more information about the color coding exposed to the user for avoiding confusion. 

This could be achieved by adding a pixmap next to the selector where on hovering with the cursor a popup with a kind of a legend will be displayed in the tooltip listing all colors and descriptions

**Comment by che85** [comment]
I added a tooltip that gives more information about the color coding

![image](https://cloud.githubusercontent.com/assets/10195822/26226346/d179f03c-3bf9-11e7-9068-5950ee9de9fd.png)


@fedorov What do you think?

**Comment by fedorov** [comment]
Looks very helpful!
