### ISSUE TITLE
Intraop Directory Structure 

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#28]
We need to specify the directory structure for intraop data. 

Case PCAMRGBX-00137_20050607_1301_20050607_1301 of @PeterBehringer has:

Intraop
-- Series
-- -- DICOM
-- -- -- DICOM files
-- -- SNAPSHOTS

Expected was:
Intraop
-- all DICOM files

**Comment by fedorov** [comment]
No, this is not an issue. The data is organized in Peter's example data this way simply because this is how it is exported from XNAT. For the AMIGO cases we should assume flat list of files for intraop data.

**Comment by che85** [comment]
Ok good to know
