### ISSUE TITLE
SliceTracker prompts user asking to save data even though no data changed

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#296]
Don't ask saving every time when Slicer quits if data should be saved even though nothing changed

**Comment by lassoan** [comment]
When you open the Save data dialog, do you see a checkmark next to any of the nodes?

**Comment by che85** [comment]
Oh I should have specified that this is not the save dialog from Slicer. It's my own dialog asking to save data specifically for SliceTracker...

**Comment by lassoan** [comment]
You may use Slicer's built-in mechanism for determining if nodes have to be saved or not. It works quite well. It uses an additional StorableModified timestamp.

**Comment by che85** [comment]
Even though I am only loading a case into SliceTracker, when using Slicer built-in save data dialog some of them are checked for saving which shouldn't be the case. I need to check that.
