### ISSUE TITLE
Preop directory selection

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#3]
When selecting the preop directory, the file data structure must be parsed depending on the structure used for saving in PCampReview Preprocessor: https://github.com/fedorov/PCampReview 

This file data structure is as follows:

RESOURCES
|-- ##
    |-- DICOM
    |-- Reconstructions
        |-- ##.nrrd
        |-- ##.xml
        |-- e.g. WholeGland.nrrd
        |-- ...

In order to use the right reconstruction and possible segmentations. All case directories must be parsed for the right t2ax image. If next to this nrrd file are other segmentations found, then these labels should be provided within the module. The user shall be able to select the labels which later can be used to create preop segmentations.

**Comment by che85** [comment]
changed from bug to enhancement

**Comment by fedorov** [comment]
Christian, let's discuss this before you do any work
