### ISSUE TITLE
ENH: target definition in Intraoperative image

### ISSUE THREAD

**Issue by leochan2009** [SlicerProstate/SliceTracker#300]
Clinician request.
Currently it is only possible to modify the predefined targets.
It will be helpful if adding targets in the intraoperative image is possible.

**Comment by che85** [comment]
This would only make sense in the segmentation step where in non-preop mode targets would be defined. By default I could just display the TargetCreationWidget there for the CoverProstate image and that should solve the issue.

**Comment by che85** [comment]
After discussing with @leochan2009:

Kemal wants to be able to set a target on the received CoverProstate image optimally even before doing any registration. 

That would have to be done within the segmentation step!

TODO:
- [ ] temporary list that holds the "added" target
- [ ] after registration "added" target should be merged into registered target lists

**Comment by leochan2009** [comment]
Confirmed with Kemal,  setting targets when the intraop image arrives, but before the registration.

**Comment by che85** [comment]
Alright. Great. Thanks for confirming!
