### ISSUE TITLE
August 02 2017 issue log

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#303]
1. case:
* registration results: window level of preop is a lot brighter than on previous SliceTracker version
* in overview step:
  * in side by side view the fiducial size suddenly is a lot bigger
  * on selection of Cover Prostate 'Registration Evaluation' collapsible button doesn't show anything: expected are sliders 
* it would be nice to add Four Up Quantitative layout to SliceTracker for displaying the DisplacementCharts besides the slice views

![image](https://user-images.githubusercontent.com/10195822/28876147-3586b69e-7766-11e7-818d-9f0fbeead164.png)

---
2. case:
* there is something off with the registration, which really needs to be checked. Not sure if something changed in the registration?
---

3. case:

**Comment by lassoan** [comment]
> there is something off with the registration

If you have time, I would really recommend to try Elastix for registration. I've been using plain ITK registration framework and BRAINS for several years and kind of accepted that registration is unpredictable, you have to tune a lot of parameters for each problem, etc. After all this pain it was quite shocking to see that Elastix just worked, every time, without parameter tuning, with reproducible results, for all kinds of images.

You can use SlicerElastix extension from the GUI or from your own module. Currently on Mac there is a shared library packaging issue, so you have to install elastix binaries manually and set the path in the module GUI (see https://github.com/lassoan/SlicerElastix/issues/2).

**Comment by che85** [comment]
I would definitely want to give that a try. I also noticed that the ITK Brains registration got worse since they made all the changes from ITK3 to ITK4. I remember doing prostate biopsies with the old approach using Slicer 3 worked more robust than the current approach.

**Comment by fedorov** [comment]
Yes, it would be interesting to evaluate it. It is also a good use case to demonstrate how modular SliceTracker can be to introduce new registration approaches. My only concern is the timeline.

@lassoan when I used Elastix last time (about 7-8 years ago probably), it was not trivial to tune the parameters, and you would need to start with some initial settings file. How do you start from scratch these days?

**Comment by lassoan** [comment]
I always use the default "generic (all)" preset (you can select it on the GUI or use it from your own module similarly how it is done [here](https://github.com/moselhy/SequenceRegistration/blob/master/Elastix4D/Elastix4D.py#L369-L374)). The beauty of elastix that this default preset (without any parameter tuning) worked well for at least 10 completely different registration cases that I've tried (various organs, imaging modalities), at least as good or better than heavily parameter-tuned BRAINS.

There is a large database of sample config files (most of them bundled with SlicerElastix) that are tailored for specific registration cases. I usually find the generic preset working better than these specialized ones, but you can get ideas from these special config files, if you need to adjust the registration behavior.

**Comment by che85** [comment]
Ok I installed it and will give it a try. The UI looks definitely better then the BRAINS one and is less confusing.

![image](https://user-images.githubusercontent.com/10195822/28926383-a03ccd8c-7835-11e7-9fbd-085a76799572.png)

**Comment by che85** [comment]
@lassoan Output volumes and transforms are not produced for any type if registration (rigid, affine, bSpline), right? In SliceTracker we designed it the way the we always provide all those registration result types to the user while evaluating.

**Comment by lassoan** [comment]
Resampled moving volume is the `Output volume`, computed transform is the `Output transform`.

It's not very nice that Elastix can only save the output transform as a displacement field transform. Elastix developers said it should be no major problem implementing that and I guess if enough people will ask for it then they will implement it sooner (here is the ticket: https://github.com/SuperElastix/elastix/issues/18, add a note there telling who you are and why you would need this feature).

**Comment by che85** [comment]
Closing this issue and creating a new feature request for Elastix registration
