### ISSUE TITLE
Issues from 9/27 Biopsies

### ISSUE THREAD

**Issue by Kmacneil0102** [SlicerProstate/SliceTracker#322]
- [x] Slicer crashed during first "processing" dialog using new SliceTracker version (case number 586)
- [x] Automatic segmentation for preop discussion: At the moment, have to wait for Kemal to have placed the targets before automatic segmentation takes place. Sometimes this is very close to the actual start of procedure (or even after he has prepped the patient and the first image is taken) and as a result if any issues arise from segmentation (needs to be retried or modified), this could interfere with start of the workflow
- [x] Asked if preop used endorectal coil twice if automatic segmentation is used; once when prompted for automatic segmentation and once for bias correction. More optimal option would be to only be ever asked once.
- [x] Slicer crashed after trying to retry the cover prostate segmentation manually after automatic segmentation was done. Process was: Automatic segmentation -> Uncheck "Use deep learning" check box -> Retry registration. Caused by an error in the usage of Segment Editor; same error with the "ImageToWorldMatrix" step previously seen.
- [x] In evaluation step, displacement of the series' prior to the currently evaluated series are not displayed correctly.. the correct displacement's are calculated upon returning to overview step.
- [x] After case closed, status/progress bar still had sliver of blue in the bar.
![20170927_120819](https://user-images.githubusercontent.com/22458394/31094698-0eb4b4f0-a784-11e7-93da-c8eb8fa8da8b.jpg)
- [x] During one case, the endorectal coil verification dialog for the automatic segmentation was very large and almost filled the screen.
![20170927_130001](https://user-images.githubusercontent.com/22458394/31094839-81adcabe-a784-11e7-9544-0cab68f37f46.jpg)

**Comment by lassoan** [comment]
If you can describe how to reproduce the crash around Segment Editor then I can fix it.

**Comment by Kmacneil0102** [comment]
@lassoan Just tested and steps for recreating: 
- Open SliceTracker and start new case.
- Choose "no preoperative data available" in dialog
- Click the "Simulate intraop reception" button under "Training Incoming Data Simulation" section.
- Ensure "use deep learning" is enabled under the SliceTracker settings button.
- Click the red "track targets" button next to the series selection.
- After segmentation runs, place a target and click the checkmark to confirm the target list.
- Click the "Quick mode" button under SurfaceCut Segmentation. Confirm overwrite when dialog appears.
- Create a contour and click the check box to confirm. The error should appear here!

Hopefully that is easy enough to follow, not sure how familiar you are with the SliceTracker workflow.

**Comment by lassoan** [comment]
I'm not familiar with the workflow. I would need a much more detailed description, test data, etc. Also, I work on Windows and I have not set up DeepInfer extension yet. It may be easier if you could drill down a bit more and provide a simpler list of steps. Maybe you can save the scene just before the crash occurs and I can load that scene and continue from there.
