### ISSUE TITLE
Zframe registration

### ISSUE THREAD

**Issue by leochan2009** [SlicerProstate/SliceTracker#323]
Dear SliceTracker team,

I am working on the prostate cryo ablation. And would like to use the zframe registration from SliceTracker.
Would it be possible to make a independent module for zframe registration , so my project won't depend on SliceTracker? 

Thanks,
Longquan

**Comment by fedorov** [comment]
Longquan, we have several pressing deadlines at the moment, so I am not sure when we would get to this. How about you factor this functionality out yourself?

Also, dependency on SliceTracker is quite light, most of it is just python - what is the specific concern of depending on SliceTracker?
