### ISSUE TITLE
White rectangles instead of annotations

### ISSUE THREAD

**Issue by PeterBehringer** [SlicerProstate/SliceTracker#33]
appears after i clicked green "check-button" when i was done with quick segmentation.

![screen 2015-09-20 um 12 48 19](https://cloud.githubusercontent.com/assets/6794629/9980352/e9731f5c-5f95-11e5-8073-c4b2a21cc4c9.png)

**Comment by che85** [comment]
@PeterBehringer What is the date of your slicer installation? I would try to reproduce this...

**Comment by PeterBehringer** [comment]
@che85 I am using latest nightly build

**Comment by fedorov** [comment]
Peter, you are talking about the white rectangles in place of annotation text?

Annotations were developed by @mehrtash, maybe he has some ideas what is happening here.

**Comment by PeterBehringer** [comment]
yes, the white rectangles.

**Comment by che85** [comment]
@PeterBehringer Do you still have these issues? I could not reproduce it on my machine.

**Comment by che85** [comment]
@mehrtash I have the same issues with the nightly build version of Slicer (2015-10-05). The annotations are not displayed properly.

![image](https://cloud.githubusercontent.com/assets/10195822/10345705/80a06c02-6cf9-11e5-8d16-169164407411.png)

**Comment by fedorov** [comment]
@pieper @jcfr any ideas what could have caused the regression?

**Comment by jcfr** [comment]
In the context of an other project, I was planning on fixing/investigating that issue this afternoon.

Stay tuned.

**Comment by jcfr** [comment]
This is also reproducible in the nightly build.

**Comment by pieper** [comment]
Yes, I have seen it too but have not had a chance to look into it.  Thanks @jcfr for investigating!

**Comment by jcfr** [comment]
FYI - Issue has also been fixed in upstream VTK.

On Thu, Oct 29, 2015 at 10:46 AM, Christian Herz <notifications@github.com>
wrote:

> Closed #33 <https://github.com/SlicerProstate/SliceTracker/issues/33>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SlicerProstate/SliceTracker/issues/33#event-449293782>
> .
>



-- 
+1 919 869 8849
