### ISSUE TITLE
Timestamps for all data received/stored

### ISSUE THREAD

**Issue by Kmacneil0102** [SlicerProstate/SliceTracker#330]
JSON file should have timestamps included for all data that is received or stored (needle images, etc.)

- [x] preop/intraop segmentation 
  - [x] manual/automatic
  - [x] start/end time
  - [x] userModified
- [x] registration
  - [x] start/end time

**Comment by fedorov** [comment]
+ including derived data - segmentations, registration results, etc

**Comment by che85** [comment]
for the reference: https://gist.github.com/che85/6bb9492e0e03c7ced681e0accf4a2ae0
