### ISSUE TITLE
(maybe) bugs, that need to be checked (found during prospective evaluation)

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#344]
- [x] Four-Up Quantitatuve view messes up z-Frame calibration step
- [x] if no preop was used, then Cover Prostate segmentation information about algorithm was not available 
- [x] one results.json had an empty entry `preop` which was not right --> this case had preop, manually segmented: 
two possible scenarios come to my mind: 
(a) segmentation was done in mpReview, Slicer crashed and user reopened it or 
(b) normal workflow and it just didn't get saved in the JSON. --> I corrected that information manually 
NOTE: this case was the first case of the prospective evaluation and we installed a newer version after that. I couldn't find the same problem again in later cases
- [x] retrying registration several times, register and retry again —> check the file names of labels:
  - NOT REPRODUCIBLE: I noticed that in one of the results.json files where ...label name was
`1216-AX-TSE-T2-GUIDANCE-FOR-NEEDLE-at-FIX-_H0-label_Retry_1_Retry_2.nrrd` 
instead of 
`16-AX-TSE-T2-GUIDANCE-FOR-NEEDLE-at-FIX-_H0-label_Retry_2.nrrd` --> I corrected that
- [x] target selection doesn't jump to right position in slice viewers anymore during evaluation step

**Comment by che85** [comment]
@fedorov I noticed, that we were not tracking the time of `Cover Template` received. What we can do though, check the laptop for those files and get the timestamps from there. Since it's only 9 cases, I will do that on Friday.

**Comment by fedorov** [comment]
It happens! We should have checked the accuracy of data capture after the first case, but of course it is always easy to say this in the retrospect. Sounds like we still have most of the data we would need captured properly, and that is most important.
