### ISSUE TITLE
Patient Selector needed

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#36]
Do we really need the patient selector? Since we load peop data, patient information can be extracted from there, right? 

Anyway we need to use the DICOM data.

**Comment by fedorov** [comment]
I guess the question is how we load the preop data.

Currently, in PCampReview, there is a concept of project directory, which may contain multiple folders. It would then make sense for SliceTracker to work with the same project directory. But if SlicerTracker takes patient directory, then you are right - we don't need it.

Can you give me a demo of the workflow tomorrow?

**Comment by PeterBehringer** [comment]
Yes, lets discuss this tomorrow. I am available until your noon (1 pm boston time).
