### ISSUE TITLE
Patient Selector, preop data and intraop data are not properly checked for the same ID

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#37]
The user is only notified about differences between the selected patient ID and the intraop data which is not valid. The user could also select a preop directory with data of a completely different patient.

**Comment by che85** [comment]
I know that there is now patient information saved in NRRD but we should find a good workflow for the selection...

Imagine, the user selects accidentally preop data of another case ... he/she should see that within labels but can we really ensure that this issue does not appear?

**Comment by fedorov** [comment]
I guess this issue is mixed with #36, I replied to that one. I don't exactly understand what you mean. Let's discuss tomorrow. @che85 can you demo the workflow for me tomorrow at SPL?

**Comment by che85** [comment]
Sure
