### ISSUE TITLE
Intraop series listview should always display all available series

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#42]
After new data has been arrived, the series listview should still show all available series and not only the new arrived series

**Comment by che85** [comment]
Do we really always want to see ALL available series? 

I also could imagine to display series, that:
- just arrived
- have not yet been used for registration

**Comment by PeterBehringer** [comment]
yes. but like before, the list should suggest the earliest needle confirmation image by setting that one to checked.

**Comment by che85** [comment]
Sorry I don't know why it was reopened again.
