### ISSUE TITLE
PatientWatchBox displays the current date

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#45]
The PatientWatchBox should display information retrieved from the DICOM database. The study date actually is the current date, which should also be retrieved from DICOM...

![image](https://cloud.githubusercontent.com/assets/10195822/10062400/44df3d66-6230-11e5-9405-ac4c7093b2ec.png)

**Comment by che85** [comment]
@fedorov Or is todays date correct to be displayed in that patientWatchBox?

**Comment by fedorov** [comment]
No, it should be the DICOM StudyDate.

Thinking about this now, it should display two dates: date of the diagnostic study, and the date of the intraop imaging study.

**Comment by che85** [comment]
Yes makes sense.
