### ISSUE TITLE
Remove PatientSelector by only using DICOM from preop

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#46]
Instead of using a patient selector, the patient information should be retrieved from the preop data:
- below the PCampReview directory structure, we also can find DICOM files (organizing DICOM with PCampReviewProcessor should be a requirement)
- retrieving the information from the very first DICOM file should work fine and we can get rid of the patient selector and doing proper checking of patientID between preop and intraop data selection

This issue is marked as high because it's very important that preop and intraop belong to the same patient.

**Comment by fedorov** [comment]
I agree with you. Since the patient information is already available in preop, and it must match intraop, there is no need to duplicate, it might just confuse the user.
