### ISSUE TITLE
storescp should be initialized and establish connection to DICOM workstation

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#5]
see Modules/Scripted/DICOMLib/DICOMProcesses.py line 115

User needs to be notified that connection to DICOM workstation is estabilshed (using echoscu DCMTK tool)

**Comment by che85** [comment]
@fedorov Should we just start the storeSCP process when the user has selected the intraop directory?

**Comment by fedorov** [comment]
Yes, it should definitely be started automatically.

**Comment by che85** [comment]
@fedorov What are we going to do with storescp? Since we need to listen to port 104 we need to have sudo access

**Comment by che85** [comment]
Since we had this issues of not being able to run a sudo storescp from Slicer without the password we should use user defined ports which don't need to use sudo.

On https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers you can see used ports.

I propose to use 13074 for storescp

**Comment by che85** [comment]
An even better idea would be to provide a range of ports just to make sure that the desired port is not in use. If that is possible with the Amigo workstation to change the port easily. 

We also could have a preferred port and optional ones as a fallback.

The used port should be displayed in SliceTracker then.

**Comment by fedorov** [comment]
here is another option - it should be possible to open those ports without sudo: http://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-1024-on-l

**Comment by che85** [comment]
I wouldn't do that because:

1. it could be a security issue
2. users who want to use that extension first need to open those ports and I could imagine that some users would not like that we assume to open a port which should only be used by sudo.

**Comment by fedorov** [comment]
yes, I agree. It is also platform-dependent. We need to check how to change the port settings on the AMIGO MR console.
