### ISSUE TITLE
Check if a series already has been registered once

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#50]
When a series already was used during the registration process and the user did not start the whole process from the beginning, there should be a warning, that the selected series has already been used. 

Otherwise the user could accidentally select a needle guided series which already was registered....

This could be done by holding a list of SeriesInstanceUIDs

**Comment by fedorov** [comment]
We should think about something like "Accept" button in the registration evaluation step. When a registration result is accepted, it should not be possible to modify it, and the corresponding needle confirmation image should be marked and disabled for future selection.

**Comment by PeterBehringer** [comment]
I like the accept button! Next to that, we should think of a "Retry" button, that can be used if registration failed. For example, if very strong motion appeared between two needle images and our mask-propagation method is not sufficient)

By clicking the button, the user should be able to re-run registration but with a manual segmentation of the gland in the current needle confirmation image. therefore, the user should be guided to segmentation step to do the contouring in the current needle image. after clicking the green check button, registration step can be automatically applied and the user finds him/herself in evaluation step again.

**Comment by fedorov** [comment]
Yes, this is a good point Peter made. What I forgot to mention last time we talked, Christian, is that if re-registration fails, the first thing to do is to segment the needle confirmation image (it is initially registered without that segmentation, and in most cases it works fine).
