### ISSUE TITLE
Allow recreation of segmentation in case of inadequate registration caused by patient movement

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#57]
While patients can move a lot during cases, it's appropriate to provide the possibility to recreate the segmentation for the "difficult" needle image.

**Comment by fedorov** [comment]
From talking to Peter, I thought it was supposed to already be possible, so I am not sure if it is an enhancement, or a bug!

**Comment by PeterBehringer** [comment]
No, its not yet possible. In #50 we talked about the "Retry-Button", which whould be implemented. @che85 is it clear for you what that button should do, or do you want to talk about that?

**Comment by che85** [comment]
@PeterBehringer Maybe you can write down, what exactly should be done when "Retry-Button" is pushed?

**Comment by fedorov** [comment]
Christian, it should load the last needle image, user should do segmentation, and then it should do registration of the cover prostate image (with segmentation) to the last needle confirmation image with segmentation.

**Comment by che85** [comment]
Just to clarify:
1. User pushes button "Retry"
2. System goes to Tab 2 for creating Segmentation on needle image (where registration failed)
3. Registration is done with:
  a. moving volume: Cover Prostate registration (would be the fixed volume)
  b. fixed volume: needle image

Is there anything else I should be aware of when doing registration? What about the parameters?

@fedorov  you mentioned something about ROI centroid?

Since there was some reason for failing of registration, should we do the rigid, affine and bspline?

**Comment by fedorov** [comment]
Christian, look at the initial registration (cover prostate to first needle image), I think you should use exactly same parameters (it includes center of ROI initialization)

**Comment by che85** [comment]
Ok I already thought so. Thanks

**Comment by PeterBehringer** [comment]
@che85 we dont take cover prostate registration as moving volume for registration, but the diagnostic preop t2

**Comment by fedorov** [comment]
@PeterBehringer is this right? I would not do this (and that's not what I did in my experiments). Registering preop T2 to needle confirmation T2, instead of cover prostate intraop T2, makes the task unnecessarily harder.

**Comment by PeterBehringer** [comment]
yes, you are right. Sorry about the confusion.
