### ISSUE TITLE
Selection of Reference Volume in label creation tab has no effect

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#59]
While being in tab 2 label creation and selecting another reference volume, the actual displayed volume does not change and segmentation is still done on the initially set reference volume!

**Comment by che85** [comment]
@fedorov Before I start fixing this issue, should it be possible to select more than one series in first step? Since the segmentation is usually done on the COVER PROSTATE, I don't see the need to allow multiple selection which automatically would invalidate this issue.

**Comment by fedorov** [comment]
This can wait until we finalize the redesign plan in #64

**Comment by che85** [comment]
set to wontfix, because the new design does not support the functionality, to select several series for the segmentation step to be loaded and afterwards to be selected as reference image.
