### ISSUE TITLE
Improve User Experience

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#64]
Since the functionality nearly is complete, it's important to provide the best possible **usability**.

We need to think about:
-  **Namings**
  - Buttons
  - Slice Annotations
    - confusing that annotations are called PREOP and INTRAOP:
      - left: displays currently acquired image with registered BSpline volume to lay over **—>** COMPARISON ORIGINAL/REGISTERED
      - right: displays currently acquired image  **—>** naming COVER PROSTATE or NEEDLE IMAGE or REGISTERED TARGETS?

- **UI element positioning**
  -  ...
- **Feedback**
  - Specific prompts
  - (more) Guidance

**Comment by fedorov** [comment]
Here's the initial sketch of the proposed refactored GUI. The idea is to reduce the number of GUI elements, reduce the number of tabs, and streamline user interaction.

I discussed this with @che85 today, and next I will create a google document with a more detailed sketch that three of us can discuss before proceeding to implementation. I will share the doc with you and will add a link here.

![img_20151023_115827599](https://cloud.githubusercontent.com/assets/313942/10698193/c9ba2d7a-797d-11e5-8e32-0fda60300423.jpg)

**Comment by PeterBehringer** [comment]
thanks for sharing!

**Comment by PeterBehringer** [comment]
@fedorov @che85 did you guys thought about integrate the z-frame registration sooner or later?

**Comment by fedorov** [comment]
Yes, we did talk about this. Our plan is to "lead the way" by focusing on developing a finished product that we are happy with. Once that is done, we will coordinate with Junichi. I did mention this to him. I don't want to get into that integration now, because it will again distract us from refining the user interface and delay deployment.

**Comment by fedorov** [comment]
Guys, I finished the first iteration of the [new GUI design draft](https://docs.google.com/document/d/1LSqnD6ROqavRTsnaqcGMecqaebr6iz64jvLLd4YnMq0/edit?usp=sharing). Let's discuss here and/or in the comments in the document, let me know what you think!
