### ISSUE TITLE
Behavior after target selection from target table 

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#76]
Changes from #72 affects partly the following behavior when selecting a target from target table.

Old behavior was:
- jump viewers to registered targets (which also affects the Biopsy Plan Viewer), even when the target was not visible in both viewers.

Expected behavior is:
- jump to selected target in Biopsy Plan Viewer (unregistered) and Tracked Targets Viewer (registered)

**Comment by fedorov** [comment]
Also need to make sure rotate to slice plane (not sure what is the exact name) is called on each volume (maybe it already is). I don't have time to look up right now.

**Comment by che85** [comment]
@fedorov To me it seems as if the slice plane is already correctly set.

**Comment by fedorov** [comment]
:+1: ok then! just checking
