### ISSUE TITLE
Improve interface based on AMIGO experience

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#83]
Some suggestions based on AMIGO trials:
* add notification when a new series becomes available
* registration evaluation step does not show labels on the slice viewer about what the image shown is (registered/intraop)
* should have a button to skip a series from the main screen of the module
* white on bright yellow in the series selection dropdown is not a good choice of color combination :-)
* initially, when the case is started, small and large text both are shown for each target - this appears to be because mpReview and SliceTracker were used during the same session, so the targets created by mpReview remain visible. Need to make sure that there is only one set of fiducials is displayed at a time.
* on the main screen of the module, there should be a button to switch between side-by-side and 4-up (or 3-over-3) layout to be able to better track the needle in the reconstructed views (sag/cor)
* also add a button for displaying the crosshair
* target annotation text is too big for the registration results slice view. It may actually be better not to show any text at all, since the name of the target is available in the module panel, instead change the color of the selected target to differentiate it from another one, if there are multiple targets on one slice
* after registration is completed, FOV for the planning series is reset. We need to set FOV for the planning and registered images independently to make sure they are centered and the slice is selected based on the position of the target
* Kemal suggested that registration for the incoming series could/should be done automatically

**Comment by che85** [comment]
@fedorov I am going to create separate issues from your text

**Comment by fedorov** [comment]
I think might be too much overhead a new issue for every single comment here

**Comment by che85** [comment]
@fedorov How would you like to have the notification about new incoming data? Also be aware of the different modes (targeting and evaluation)

**Comment by fedorov** [comment]
How about a popup notifying the user that there is a new dataset, and then several buttons with choices: "Register", "Postpone", "Ignore"? (anything else?) We can also have a checkbox "Do not notify again".

If the user selects Register, it either goes to segmentation+registration, or does registration automatically and when done goes to evaluation. When Postpone is selected - no action, everything proceeds as it is right now. Ignore will grey out the new incoming series. What do you think?

**Comment by che85** [comment]
Sounds reasonable to me.

**Comment by che85** [comment]
I am going to add the checkbox and two buttons "Track targets" and "Postpone".

What if the user checks "Do not notify again" and clicks "Track targets" how should this situation be handled the next time data is arriving? Automatically track targets? If so, what if the user is still in evaluation mode and did not yet approve the current needle image?

**Comment by che85** [comment]
@fedorov "on the main screen of the module, there should be a button to switch between side-by-side and 4-up (or 3-over-3) layout to be able to better track the needle in the reconstructed views (sag/cor)" - do you really mean the main screen? I guess it makes more sense in the evaluation step to provide such a button

**Comment by fedorov** [comment]
Probably both. The purpose of this is to track needle, which will be done outside evaluation step

**Comment by che85** [comment]
@fedorov "after registration is completed, FOV for the planning series is reset. We need to set FOV for the planning and registered images independently to make sure they are centered and the slice is selected based on the position of the target"

"We need to set FOV for the planning and registered images independently to make sure they are centered" How would you do that?
