### ISSUE TITLE
Add motion summary plots

### ISSUE THREAD

**Issue by fedorov** [SlicerProstate/SliceTracker#84]
Let's add 3 plots that would report motion in IS/LR/AP directions relative to the initial position of the prostate, based on the registration result. To do this, we can calculate the centroid of the whole gland segmentation, and for each registration apply the accepted registration result (whatever was accepted - either rigid or b-spline) to get a new point for each of the plots.

**Comment by che85** [comment]
@fedorov "whatever was accepted - either rigid or b-spline", if I got it right, then you are not thinking about "if just the registration was accepted". You are thinking about if the "rigid" or "bSpline" registration was accepted. Currently we don't differentiate between those. It's just "the registration for the currently evaluation series was accepted, skipped or rejected"

**Comment by fedorov** [comment]
> Currently we don't differentiate between those

ok, let's leave it as it is right now, and refine later if we see there is a need for picking a specific registration mode.
