### ISSUE TITLE
Add some icons to make UI more usable

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#90]
Instead of using those checkboxes, I can imagine to use some icons which indicate: a needle, a grid, a path, and a zframe

![image](https://cloud.githubusercontent.com/assets/10195822/12768979/ec542746-c9e1-11e5-9177-3df8ec609de8.png)

@fedorov What do you think? I am afraid, that it would become to complicated to first open the settings collapsible button and then select the checkboxes.

I can also imagine to replace some other buttons with self describing icons

**Comment by che85** [comment]
Maybe like that?
![image](https://cloud.githubusercontent.com/assets/10195822/12769604/3031ef8e-c9e7-11e5-8cf5-8232fa008858.png)

![image](https://cloud.githubusercontent.com/assets/10195822/12769619/3f920c3e-c9e7-11e5-9be6-877967ba852e.png)

**Comment by fedorov** [comment]
This is good, I like your proposal

On Tue, Feb 2, 2016, 19:58 Christian Herz <notifications@github.com> wrote:

> Maybe like that?
> [image: image]
> <https://cloud.githubusercontent.com/assets/10195822/12769604/3031ef8e-c9e7-11e5-8cf5-8232fa008858.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/10195822/12769619/3f920c3e-c9e7-11e5-9be6-877967ba852e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SlicerProstate/SliceTracker/issues/90#issuecomment-178929162>
> .
>
-- 

Sent from on the go
