### ISSUE TITLE
Automatically run ZFrame registration on receiving Cover Template image

### ISSUE THREAD

**Issue by che85** [SlicerProstate/SliceTracker#94]
After selection of intraop data directory, the directory is parsed for eligible DICOM data that can be used in SliceTracker. When identifying Cover Template and ZFrame Registration has not been done before, the ZFrame registration could automatically be executed.

One issue would be if one Cover Template was transferred and then another is send because the first didn't cover the whole ZFrame (or similar issues)

**Comment by che85** [comment]
@fedorov And after doing ZFrame Registration and going back to first step, SliceTracker could check if there already has been received a Cover Prostate image and could immediately switch to the segmentation step instead of waiting for the user to click "track targets" for getting into that step. Anyway the user doesn't have any other possibilities to do anything else in between.

**Comment by che85** [comment]
> TODO: need to think about possible issues like bad quality of Cover Prostate image which would
> actually be skipped and a new one would be taken instead.

Anyway we need to think about that, because it could also happen that the Cover Template should be skipped. 

I propose to add a skip button in a) segmentation mode and b) zFrame registration (next to the approve registration button)

@fedorov  What do you think?

**Comment by fedorov** [comment]
I think this should be handled by a popup on scan arrival asking user to confirm to proceed with registration. If the scan is bad, then the user says no and skips the series, without even attempting the registration. Would this work?

**Comment by che85** [comment]
The image is loaded into the viewers, when "track targets" is pushed. So the user does not have any idea about the image quality before that. So anyway the user must have the option to view the see the image before deciding to skip it. If we would implement it the way you want it to be, it would actually add another "step" to SliceTracker like "Eligibility of received images".
